export const API_REQUEST = 'API_REQUEST'
export const DELETE_API_REQUEST = 'DELETE_API_REQUEST'

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'

export const INCREMENT_PRODUCT_QUANTITY = 'INCREMENT_PRODUCT_QUANTITY'
export const DECREMENT_PRODUCT_QUANTITY =  'DECREMENT_PRODUCT_QUANTITY'